Dockerize tool
jcapels/boimmg pull request #4
Opened 2022-11-28 17:02 UTC by AdrianoSilva19

2022-12-05 16:54 UTC, jcapels requested changes

2022-12-05 16:54 UTC, jcapels commented on Dockerfile
> +CMD ["python","tests/unit_tests/test_etl.py"]
deves pôr o dockerfile como estava antes, porque este está na root. Podes pôr numa pasta na root e podes chamar-lhe pipelines/synonyms_etl

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/lipid_maps.py
> +sys.path.insert(1, '.')
para que serve isto? deve ser do vscode nao? tira, a pasta tem de estar limpa destas coisas.

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/lipid_maps.py
> +log,user,password = CompoundsDBAccessor.read_config_file()
Isto deve estar no init de cada classe. Este ficheiro deve ser apenas de classes, não deve ter nada para correr fora das classes

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/lipid_maps.py
> +data_base_connection = GraphDatabase.driver(uri=log,
Vê o que escrevi em cima de não ter nada fora das classes

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/lipid_maps.py
> +def get_connection_list(df: pd.DataFrame):
esta função já não vai buscar uma lista de conecções certo ? dá-lhe um nome apropriado e põe num ficheiro nesta pasta chamado _utils.py por exemplo... assim este ficheiro fica exclusivo para classes

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/swiss_lipids.py
> +log,user,password = CompoundsDBAccessor.read_config_file()
igual ao comentário de cima

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/swiss_lipids.py
> +data_base_connection = GraphDatabase.driver(uri=log,
o mesmo de cima

2022-12-05 16:54 UTC, jcapels commented on boimmgpy/etl/swiss_lipids.py
> +def get_connection_list(df: pd.DataFrame):
o mesmo de cima

2022-12-05 16:54 UTC, jcapels commented on requirements.txt
> -rdkit~=2020.09.1.0
tiraste o rdkit por alguma razão?

2022-12-05 16:54 UTC, jcapels commented on tests/unit_tests/test_etl.py
>  class TestLipidMapsETL(unittest.TestCase):
podes deixar estar aqui esta classe mas acho que devias deixar a pipeline numa pasta na root chamada pipelines/synonyms_etl

2022-12-05 18:12 UTC, AdrianoSilva19 commented on Dockerfile
> +CMD ["python","tests/unit_tests/test_etl.py"]
fazer outro dockerfile só para a minha parte?

2022-12-06 16:14 UTC, AdrianoSilva19 commented on requirements.txt
> -rdkit~=2020.09.1.0
está lá na mesma mas sem identificar uma versão, se escolher uma versão dá erro

2022-12-07 10:21 UTC, merged